import {HUB_KEY,readSettings,putMemory,parseSkill,skillMarkdown,personas,contextFiles,assistantContext,expandReferences,searchSessions,normalizeTodos,sessionExport,escapeHTML as esc} from './assistant-data.js';
const $=id=>document.getElementById(id);
const features=['ذاكرة دائمة','مكتبة مهارات','بحث المحادثات','تعليمات المشروع','مراجع @','شخصيات الوكيل','خطة مهام','مزود احتياطي','قراءة صوتية','تصدير المحادثة'];
export function createAssistantHub(context){
  let settings=readSettings(localStorage),projectId=null,referenceItems=[],referenceIndex=0,utterance=null;
  const current=()=>context.getChat();
  function state(){const chat=current();if(!chat)return {profile:'developer',skills:[],todos:[]};chat.assistant ||= {profile:'developer',skills:[],todos:[]};return chat.assistant}
  function persist(){localStorage.setItem(HUB_KEY,JSON.stringify(settings))}
  function action(fn){return async event=>{try{await fn(event)}catch(error){context.toast(error.message)}}}
  function save(){context.save();refresh()}
  function mount(){
    const tab=document.createElement('button');tab.dataset.tab='assistant';tab.textContent='الوكيل';document.querySelector('[data-tab="task"]').after(tab);
    const panel=document.createElement('div');panel.id='assistantTab';panel.className='ws-body hidden';panel.innerHTML='<div class="preview-note">10 إضافات مستوحاة من Hermes Agent · تعمل مع مساحة AiWay الحالية</div><div id="assistantContent" class="assistant-content"></div>';document.querySelector('#workspace').append(panel);
    const shortcut=document.createElement('button');shortcut.id='assistantHubButton';shortcut.className='side-btn';shortcut.innerHTML='<span aria-hidden="true">✦</span> قدرات الوكيل';$('sidebarSettings').after(shortcut);shortcut.onclick=context.open;
    $('assistantContent').innerHTML=`<div class="hub-features">${features.map((name,i)=>'<span><b>'+String(i+1).padStart(2,'0')+'</b> '+name+'</span>').join('')}</div>
      <details class="hub-section" open><summary>الذاكرة الدائمة <small>ملاحظات تختار إرسالها في الطلبات القادمة</small></summary><form id="hubMemoryForm"><input id="hubMemoryId" type="hidden"><label>عنوان الملاحظة<input id="hubMemoryTitle" maxlength="80" required placeholder="مثل: أسلوب تصميم المشروع"></label><label>الملاحظة<textarea id="hubMemoryText" maxlength="2000" required placeholder="معلومة أو تفضيل تريد أن يتذكره الوكيل"></textarea></label><div class="hub-row"><label>النطاق<select id="hubMemoryScope"><option value="global">كل مشروعاتي</option><option value="project">هذا المشروع فقط</option></select></label><button class="primary-mini">حفظ الملاحظة</button><button type="button" id="hubMemoryClear" class="secondary-mini">مسح النموذج</button></div></form><div id="hubMemoryList" class="hub-list"></div><p class="hub-hint">تُحفظ في هذا المتصفح؛ أضف ما تريد إرساله للنموذج فقط. يمكن تعطيل أي ملاحظة.</p></details>
      <details class="hub-section"><summary>مكتبة المهارات <small>استيراد SKILL.md وتفعيل المهارات عند الحاجة</small></summary><div id="hubSkillsList" class="hub-list"></div><form id="hubSkillForm"><input type="hidden" id="hubSkillId"><label>ملف المهارة<textarea id="hubSkillMarkdown" spellcheck="false" dir="ltr" placeholder="---&#10;name: my-skill&#10;description: Short description&#10;---&#10;&#10;Instructions…" required></textarea></label><div class="hub-row"><button class="primary-mini">حفظ المهارة</button><button type="button" id="hubImportSkill" class="secondary-mini">استيراد ملف MD</button><button type="button" id="hubNewSkill" class="secondary-mini">مهارة جديدة</button></div><input type="file" accept=".md,.markdown" id="hubSkillInput" hidden></form><p class="hub-hint">حتى 3 مهارات مفعّلة لكل مشروع. تعليمات نصية يقرأها النموذج، ولا تُشغّل ملفات أو سكربتات تلقائيًا. زر «احفظ كمهارة» بجوار الرد يجهز مسودة للمراجعة.</p></details>
      <details class="hub-section"><summary>البحث في المحادثات <small>العنوان ونص الرسائل في جميع المشروعات</small></summary><label>كلمات البحث<input id="hubSessionQuery" type="search" placeholder="ابحث عن حل أو خطأ سابق…"></label><div id="hubSessionResults" class="hub-list"></div></details>
      <details class="hub-section"><summary>تعليمات المشروع ومراجع @</summary><label class="hub-check"><input type="checkbox" id="hubContextFiles"> تحميل AGENTS.md و.hermes.md وCLAUDE.md وSOUL.md و.cursorrules</label><div id="hubContextList" class="hub-list"></div><label class="hub-check"><input type="checkbox" id="hubReferences"> إرفاق مراجع الملفات المكتوبة بـ@</label><p class="hub-hint">اكتب @src/app.js أو @{مسار فيه مسافات} أو @src/ لإرفاق مجلد. @diff يرفق التعديلات المقترحة. تظهر قائمة اقتراحات أثناء الكتابة. تعليمات المشروع تتبع خيار سياق المشروع في تبويب «السياق».</p><button id="hubInsertReference" class="secondary-mini">إضافة مرجع إلى الطلب</button></details>
      <details class="hub-section"><summary>شخصية الوكيل <small>اختيار خاص بكل مشروع</small></summary><label>أسلوب المساعد<select id="hubPersona">${personas.map(p=>'<option value="'+p.id+'">'+p.name+'</option>').join('')}</select></label><label>تعليمات الشخصية المخصصة<textarea id="hubCustomPersona" maxlength="2000" placeholder="اكتب أسلوب العمل الذي تريده…"></textarea></label><button id="hubSavePersona" class="primary-mini">حفظ الشخصية</button><p id="hubPersonaHint" class="hub-hint"></p></details>
      <details class="hub-section" open><summary>خطة المهام <small>خطوات قابلة للتحديث والحفظ</small></summary><form id="hubTodoForm" class="hub-row"><input id="hubTodoText" maxlength="240" required placeholder="أضف خطوة للمشروع…" aria-label="خطوة جديدة"><button class="primary-mini">إضافة</button></form><div id="hubTodoProgress" class="hub-hint"></div><div id="hubTodoList" class="hub-list"></div><p class="hub-hint">يمكن للوكيل تحديث الخطة بأداة todo_list. تظهر خطة Codex الأصلية هنا عندما يرسلها الخادم.</p></details>
      <details class="hub-section"><summary>المزود الاحتياطي</summary><label>عند فشل مزود API قبل بدء الرد<select id="hubFallback"></select></label><p class="hub-hint">اختياري: قد تُرسل المحادثة للمزود الذي تختاره. يعمل مع Compatible وOpenRouter وGemini عند خطأ شبكة أو 408/429/5xx، مرة واحدة فقط. لا يكرر ردًا بدأ بالفعل، ولا ينقل عمليات Codex أو OpenCode.</p></details>
      <details class="hub-section"><summary>قراءة الردود صوتيًا</summary><div class="hub-row"><label>لغة الصوت<select id="hubVoiceLang"><option value="ar">العربية</option><option value="en-US">English</option></select></label><label>السرعة<select id="hubVoiceRate"><option value="0.8">0.8×</option><option value="1">1×</option><option value="1.2">1.2×</option><option value="1.5">1.5×</option></select></label></div><div class="hub-row"><button id="hubSpeakLatest" class="primary-mini">قراءة آخر رد</button><button id="hubStopVoice" class="secondary-mini">إيقاف الصوت</button></div><p id="hubVoiceStatus" class="hub-hint" role="status">يستخدم الأصوات المتاحة في المتصفح أو النظام؛ لا يحتاج مفتاح API.</p></details>
      <details class="hub-section"><summary>تصدير المحادثة</summary><label class="hub-check"><input id="hubRedactExport" type="checkbox" checked> إخفاء أنماط المفاتيح والتوكنات الشائعة</label><div class="hub-row"><button id="hubExportJSON" class="secondary-mini">تنزيل JSON</button><button id="hubExportMD" class="secondary-mini">تنزيل Markdown</button></div><p class="hub-hint">الرسائل وعمليات الأدوات ونتائج الفحص فقط؛ إعدادات الاتصال والمفاتيح ومحتوى المرفقات لا تدخل في التصدير. راجع النص قبل مشاركته، فإخفاء الأنماط لا يكتشف كل سر محتمل.</p></details>`;
    const picker=document.createElement('div');picker.id='referencePicker';picker.className='reference-picker hidden';picker.setAttribute('role','listbox');picker.setAttribute('aria-label','مراجع المشروع');$('composer').append(picker);
    $('hubMemoryForm').onsubmit=action(event=>{event.preventDefault();settings.memories=putMemory(settings,{id:$('hubMemoryId').value||undefined,title:$('hubMemoryTitle').value,text:$('hubMemoryText').value,scope:$('hubMemoryScope').value,projectId:current()?.id});persist();$('hubMemoryForm').reset();refresh();context.toast('حُفظت الملاحظة وسيستخدمها الوكيل في الطلب القادم')});
    $('hubMemoryClear').onclick=()=>$('hubMemoryForm').reset();
    $('hubSkillForm').onsubmit=action(event=>{event.preventDefault();const parsed=parseSkill($('hubSkillMarkdown').value),id=$('hubSkillId').value||crypto.randomUUID(),others=settings.skills.filter(s=>s.id!==id);if(others.length>=30)throw Error('الحد 30 مهارة');if(others.some(s=>s.name===parsed.name))throw Error('يوجد اسم مهارة مطابق؛ حرّر المهارة الحالية أو اختر اسمًا آخر');settings.skills=[...others,{id,...parsed}];persist();$('hubSkillForm').reset();refresh();context.toast('حُفظت المهارة؛ فعّلها من القائمة لاستخدامها')});
    $('hubImportSkill').onclick=()=>$('hubSkillInput').click();$('hubNewSkill').onclick=()=>$('hubSkillForm').reset();
    $('hubSkillInput').onchange=action(async event=>{const file=event.target.files[0];if(!file)return;if(file.size>64000)throw Error('ملف المهارة أكبر من الحد');const parsed=parseSkill(await file.text(),file.name);$('hubSkillId').value='';$('hubSkillMarkdown').value=skillMarkdown(parsed);event.target.value='';context.toast('تم تحميل المسودة؛ اضغط حفظ المهارة')});
    $('hubSessionQuery').oninput=renderSearch;
    $('hubContextFiles').onchange=()=>{settings.contextFiles=$('hubContextFiles').checked;persist();renderContext()};
    $('hubReferences').onchange=()=>{settings.references=$('hubReferences').checked;persist();if(!settings.references)hideReferences()};
    $('hubInsertReference').onclick=()=>{const input=$('prompt');input.value+=' @';input.focus();input.setSelectionRange(input.value.length,input.value.length);showReferences()};
    $('hubPersona').onchange=()=>{$('hubPersonaHint').textContent=personas.find(p=>p.id===$('hubPersona').value)?.instructions||'التعليمات المخصصة تُستخدم عند اختيار الشخصية المخصصة'};
    $('hubSavePersona').onclick=action(()=>{settings.customPersona=$('hubCustomPersona').value.trim();state().profile=$('hubPersona').value;persist();save();context.toast('حُفظ أسلوب الوكيل للطلب القادم')});
    $('hubTodoForm').onsubmit=action(event=>{event.preventDefault();state().todos=normalizeTodos([...(state().todos||[]),{content:$('hubTodoText').value}]);$('hubTodoText').value='';save()});
    $('hubFallback').onchange=()=>{settings.fallbackId=$('hubFallback').value;persist();context.toast(settings.fallbackId?'تم اختيار المزود الاحتياطي':'أُلغي المزود الاحتياطي')};
    $('hubVoiceLang').onchange=$('hubVoiceRate').onchange=()=>{settings.voiceLang=$('hubVoiceLang').value;settings.voiceRate=Number($('hubVoiceRate').value);persist()};
    $('hubSpeakLatest').onclick=()=>speak([...current().messages].reverse().find(m=>m.role==='assistant'&&!m.loading)?.text||'');$('hubStopVoice').onclick=stopVoice;
    $('hubExportJSON').onclick=()=>exportCurrent('json');$('hubExportMD').onclick=()=>exportCurrent('md');
    $('assistantContent').addEventListener('click',action(event=>{const button=event.target.closest('[data-memory-edit],[data-memory-delete],[data-memory-toggle],[data-skill-edit],[data-skill-delete],[data-skill-export],[data-session-open],[data-todo-delete]');if(!button)return;
      if(button.dataset.memoryEdit){const m=settings.memories.find(m=>m.id===button.dataset.memoryEdit);$('hubMemoryId').value=m.id;$('hubMemoryTitle').value=m.title;$('hubMemoryText').value=m.text;$('hubMemoryScope').value=m.scope;$('hubMemoryTitle').focus()}
      if(button.dataset.memoryDelete){settings.memories=settings.memories.filter(m=>m.id!==button.dataset.memoryDelete);persist();refresh()}
      if(button.dataset.memoryToggle){const m=settings.memories.find(m=>m.id===button.dataset.memoryToggle);m.enabled=m.enabled===false;persist();refresh()}
      if(button.dataset.skillEdit){const skill=settings.skills.find(s=>s.id===button.dataset.skillEdit);$('hubSkillId').value=skill.id;$('hubSkillMarkdown').value=skillMarkdown(skill);$('hubSkillMarkdown').focus()}
      if(button.dataset.skillDelete){settings.skills=settings.skills.filter(s=>s.id!==button.dataset.skillDelete);state().skills=(state().skills||[]).filter(id=>id!==button.dataset.skillDelete);persist();save()}
      if(button.dataset.skillExport){const skill=settings.skills.find(s=>s.id===button.dataset.skillExport);context.download(skill.name+'-SKILL.md',new Blob([skillMarkdown(skill)],{type:'text/markdown;charset=utf-8'}))}
      if(button.dataset.sessionOpen)context.loadChat(button.dataset.sessionOpen);
      if(button.dataset.todoDelete){state().todos=state().todos.filter(t=>t.id!==button.dataset.todoDelete);save()}
    }));
    $('assistantContent').addEventListener('change',action(event=>{const input=event.target;
      if(input.dataset.skillEnable){const ids=new Set(state().skills||[]);input.checked?ids.add(input.dataset.skillEnable):ids.delete(input.dataset.skillEnable);if(ids.size>3){input.checked=false;throw Error('يمكن تفعيل 3 مهارات فقط للمشروع')}state().skills=[...ids];save()}
      if(input.dataset.todoStatus){state().todos=normalizeTodos(state().todos.map(t=>t.id===input.dataset.todoStatus?{...t,status:input.value}:t));save()}
    }));
    document.addEventListener('click',event=>{const button=event.target.closest('[data-speak-message],[data-skill-from-message]');if(!button)return;const message=current()?.messages.find(m=>m.id===(button.dataset.speakMessage||button.dataset.skillFromMessage));if(!message)return;if(button.dataset.speakMessage)speak(message.text);else draftSkill(message)});
    $('prompt').addEventListener('input',showReferences);
    $('prompt').addEventListener('keydown',event=>{if($('referencePicker').classList.contains('hidden'))return;if(['ArrowUp','ArrowDown','Enter','Escape'].includes(event.key)){event.preventDefault();event.stopImmediatePropagation();if(event.key==='Escape')hideReferences();else if(event.key==='Enter')insertReference(referenceItems[referenceIndex]);else{referenceIndex=(referenceIndex+(event.key==='ArrowDown'?1:-1)+referenceItems.length)%referenceItems.length;renderReferences()}}},true);
    $('referencePicker').onclick=event=>{const button=event.target.closest('[data-reference]');if(button)insertReference(button.dataset.reference)};
    document.addEventListener('click',event=>{if(!event.target.closest('#composer'))hideReferences()});refresh();
  }
  function refresh(){if(!$('assistantContent'))return;
    if(current()?.id!==projectId){projectId=current()?.id;if(utterance)stopVoice();$('hubMemoryForm').reset();$('hubSkillForm').reset();}
    const s=state();$('hubPersona').value=s.profile||'developer';$('hubCustomPersona').value=settings.customPersona;$('hubPersona').onchange?.();$('hubContextFiles').checked=settings.contextFiles;$('hubReferences').checked=settings.references;
    $('hubVoiceLang').value=settings.voiceLang;$('hubVoiceRate').value=String(settings.voiceRate);
    $('hubMemoryList').innerHTML=settings.memories.filter(m=>m.scope==='global'||m.projectId===current()?.id).map(m=>'<div class="hub-item '+(m.enabled===false?'muted':'')+'"><strong>'+esc(m.title)+'</strong><small>'+(m.scope==='global'?'كل المشروعات':'هذا المشروع')+(m.enabled===false?' · معطلة':' · مفعلة')+'</small><p>'+esc(m.text)+'</p><div class="hub-row"><button class="secondary-mini" data-memory-edit="'+esc(m.id)+'">تعديل</button><button class="secondary-mini" data-memory-toggle="'+esc(m.id)+'">'+(m.enabled===false?'تفعيل':'تعطيل')+'</button><button class="secondary-mini" data-memory-delete="'+esc(m.id)+'">حذف</button></div></div>').join('')||'<p class="hub-hint">لا توجد ملاحظات محفوظة.</p>';
    $('hubSkillsList').innerHTML=settings.skills.map(skill=>'<div class="hub-item"><label class="hub-check"><input type="checkbox" data-skill-enable="'+esc(skill.id)+'" '+((s.skills||[]).includes(skill.id)?'checked':'')+'><strong>'+esc(skill.name)+'</strong></label><p>'+esc(skill.description)+'</p><div class="hub-row"><button data-skill-edit="'+esc(skill.id)+'" class="secondary-mini">تعديل</button><button data-skill-export="'+esc(skill.id)+'" class="secondary-mini">تنزيل SKILL.md</button><button data-skill-delete="'+esc(skill.id)+'" class="secondary-mini">حذف</button></div></div>').join('')||'<p class="hub-hint">أضف مهارة أو استورد ملفًا أولًا.</p>';
    $('hubTodoList').innerHTML=(s.todos||[]).map(t=>'<div class="hub-todo"><span>'+esc(t.content)+'</span><select aria-label="حالة المهمة '+esc(t.content)+'" data-todo-status="'+esc(t.id)+'"><option value="pending" '+(t.status==='pending'?'selected':'')+'>بانتظار التنفيذ</option><option value="in_progress" '+(t.status==='in_progress'?'selected':'')+'>قيد التنفيذ</option><option value="completed" '+(t.status==='completed'?'selected':'')+'>مكتملة</option></select><button class="icon-btn" data-todo-delete="'+esc(t.id)+'" aria-label="حذف المهمة">×</button></div>').join('');
    $('hubTodoProgress').textContent=(s.todos||[]).filter(t=>t.status==='completed').length+' / '+(s.todos||[]).length+' مهمة مكتملة';
    const providers=context.getProviders().filter(p=>['compatible','openrouter','gemini'].includes(p.type));$('hubFallback').innerHTML='<option value="">بدون مزود احتياطي</option>'+providers.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+' · '+esc(p.model||'اختر نموذجًا في الإعدادات')+'</option>').join('');$('hubFallback').value=settings.fallbackId;
    renderSearch();renderContext();
  }
  function renderSearch(){const term=$('hubSessionQuery').value.trim(),projects=context.getProjects(),results=searchSessions(projects,term);$('hubSessionResults').innerHTML=results.map(r=>'<button class="hub-search-result" data-session-open="'+esc(r.projectId)+'"><strong>'+esc(r.title)+'</strong><small>'+esc(r.role==='user'?'المستخدم':r.role==='assistant'?'المساعد':'عنوان')+'</small><span>'+esc(context.cleanText(r.snippet))+'</span></button>').join('')||'<p class="hub-hint">'+(term?'لا توجد نتائج.':'اكتب كلمات للبحث في نص الرسائل.')+'</p>'}
  function renderContext(){const names=contextFiles(context.getFiles());$('hubContextList').innerHTML=names.length?names.map(name=>'<code>'+esc(name)+'</code>').join(' '):'<p class="hub-hint">لا توجد ملفات تعليمات معروفة في المشروع.</p>'}
  function showReferences(){if(!settings.references)return;const input=$('prompt'),before=input.value.slice(0,input.selectionStart),match=before.match(/(?:^|\s)@([^\s{}"]*)$/);if(!match){hideReferences();return}const paths=Object.keys(context.getFiles()),folders=[...new Set(paths.flatMap(p=>p.split('/').slice(0,-1).map((_,i)=>p.split('/').slice(0,i+1).join('/')+'/')))];referenceItems=['diff',...folders,...paths].filter(p=>p.toLowerCase().includes(match[1].toLowerCase())).slice(0,9);referenceIndex=0;if(!referenceItems.length){hideReferences();return}renderReferences();$('referencePicker').classList.remove('hidden')}
  function renderReferences(){$('referencePicker').innerHTML=referenceItems.map((path,i)=>'<button type="button" role="option" aria-selected="'+(i===referenceIndex)+'" data-reference="'+esc(path)+'">'+esc(path)+'</button>').join('')}
  function hideReferences(){$('referencePicker')?.classList.add('hidden')}
  function insertReference(path){if(!path)return;const input=$('prompt'),end=input.selectionStart,start=input.value.lastIndexOf('@',end-1),value='@{'+path+'} ';input.value=input.value.slice(0,start)+value+input.value.slice(end);input.focus();input.setSelectionRange(start+value.length,start+value.length);hideReferences()}
  function draftSkill(message){context.open();const section=$('hubSkillForm').closest('details');section.open=true;$('hubSkillId').value='';$('hubSkillMarkdown').value=skillMarkdown({name:'session-skill-'+Date.now(),description:'مسودة من رد سابق — راجعها قبل التفعيل',body:'# خطوات قابلة لإعادة الاستخدام\n\n'+context.cleanText(message.text).slice(0,12000)});$('hubSkillMarkdown').focus();context.toast('المسودة لم تُحفظ أو تُفعّل؛ راجعها واضغط حفظ')}
  function stopVoice(){window.speechSynthesis?.cancel();utterance=null;if($('hubVoiceStatus'))$('hubVoiceStatus').textContent='تم إيقاف الصوت'}
  function speak(text){text=context.cleanText(text).replace(/```[\s\S]*?```/g,' [مقطع كود] ').replace(/(\*\*|__)(.*?)\1/g,'$2').replace(/^#{1,6}\s+/gm,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/`/g,'').trim();if(!text){context.toast('لا يوجد رد نصي مكتمل للقراءة');return}if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){context.toast('المتصفح لا يدعم قراءة النص صوتيًا');return}stopVoice();const item=new SpeechSynthesisUtterance(text.slice(0,12000));utterance=item;item.lang=settings.voiceLang;item.rate=settings.voiceRate;const voice=speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith(settings.voiceLang.split('-')[0]));if(voice)item.voice=voice;item.onend=()=>{if(utterance===item){$('hubVoiceStatus').textContent='انتهت القراءة';utterance=null}};item.onerror=event=>{if(utterance===item){$('hubVoiceStatus').textContent='تعذرت القراءة: '+event.error;utterance=null}};$('hubVoiceStatus').textContent='جارٍ قراءة الرد…';speechSynthesis.speak(item)}
  function exportCurrent(format){try{if(!current())return;const output=sessionExport(current(),{format,redact:$('hubRedactExport').checked,cleanText:context.cleanText});context.download('AiWay-conversation-'+new Date().toISOString().slice(0,10)+'.'+format,new Blob([output],{type:format==='json'?'application/json':'text/markdown;charset=utf-8'}))}catch(error){context.toast(error.message)}}
  function tool(call){if(call?.name!=='todo_list')return null;const args=call.arguments||call;if(args.items!==undefined){state().todos=normalizeTodos(args.items);save();return 'تم تحديث '+state().todos.length+' خطوة في خطة المهام'}return 'خطة المهام: '+JSON.stringify(state().todos||[])}
  function observeCodex(message){if(message.method!=='turn/plan/updated'||!Array.isArray(message.params?.plan)||!current()?.codexThreadId||message.params.threadId!==current().codexThreadId)return;try{state().todos=normalizeTodos(message.params.plan.map((step,i)=>({id:'codex-plan-'+i,content:step.step,status:step.status==='inProgress'?'in_progress':step.status})));save()}catch(error){context.toast('تعذر عرض خطة Codex: '+error.message)}}
  return {mount,refresh,tool,observeCodex,hideReferences,
    systemContext:()=>assistantContext(settings,current(),context.getFiles(),{allowFiles:context.allowProjectFiles()}),
    references:text=>settings.references?expandReferences(text,context.getFiles(),context.getPending()):{context:'',paths:[]},
    backupProvider:()=>context.getProviders().find(p=>p.id===settings.fallbackId),
    messageActions:message=>message.role==='assistant'?'<button data-speak-message="'+esc(message.id)+'">استمع</button><button data-skill-from-message="'+esc(message.id)+'">احفظ كمهارة</button>':'',
  };
}
